// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
namespace SimpleOtisAPI.Domain.Models;

public partial class SimpleOtisAPIContext : DbContext
{
    public SimpleOtisAPIContext()
    {
        
    }
    public SimpleOtisAPIContext(DbContextOptions<SimpleOtisAPIContext> options) : base(options)
    {
    }

    public virtual DbSet<tblCountryDetail> tblCountryDetails { get; set; }

    public virtual DbSet<tblLanguageDetail> tblLanguageDetails { get; set; }

    public virtual DbSet<tblPreference> tblPreferences { get; set; }

    public virtual DbSet<tblTheme> tblThemes { get; set; }

    public virtual DbSet<tblWidget> tblWidgets { get; set; }

    public virtual DbSet<DynamicMenuModel> tblDynamicMenus { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {

    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<LanguageList>(entity =>
        {
            entity.HasNoKey();

        });
        modelBuilder.Entity<DynamicMenuModel>(entity =>
        {
            entity.HasNoKey();
        });

        modelBuilder.Entity<NavigationData>(entity =>
        {
            entity.HasNoKey();
            entity.ComplexProperty(s => s.LeftNav, y => { y.IsRequired(); });
            entity.ComplexProperty(s => s.Footer, y => { y.IsRequired(); });
        });

        modelBuilder.Entity<tblCountryDetail>(entity =>
        {
            entity.HasKey(e => e.Country_Id).HasName("PK__CountryD__8036CBAE71E03740");
        });

        modelBuilder.Entity<tblLanguageDetail>(entity =>
        {
            entity.HasKey(e => e.Language_Id).HasName("PK__Language__B7596FF342F331CE");

            entity.HasOne(d => d.Country).WithMany(p => p.tblLanguageDetails)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LanguageD__Count__3E52440B");
        });

        modelBuilder.Entity<tblPreference>(entity =>
        {
            entity.HasKey(e => e.Preference_Id).HasName("PK__tbl_Pref__B18CAC43E7C466D3");

            entity.HasOne(d => d.Theme).WithMany(p => p.tblPreferences).HasConstraintName("FK__tbl_Prefe__Theme__440B1D61");

            entity.ComplexProperty(c => c.LanguageList, y => { y.IsRequired(); });
        });

        modelBuilder.Entity<tblTheme>(entity =>
        {
            entity.HasKey(e => e.Theme_Id).HasName("PK__Theme__592407B2E8C8C286");
        });

        modelBuilder.Entity<tblWidget>(entity =>
        {
            entity.HasKey(e => e.Widget_Id).HasName("PK__WIDGET__17959799224FCEED");

            entity.HasOne(d => d.Country).WithMany(p => p.tblWidgets)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__WIDGET__Country___403A8C7D");

            entity.HasOne(d => d.Language).WithMany(p => p.tblWidgets)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__WIDGET__Language__412EB0B6");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}