// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SimpleOtisAPI.Domain.Models;

public partial class tblCountryDetail
{
    [Key]
    public int Country_Id { get; set; }

    [Required]
    [StringLength(3)]
    [Unicode(false)]
    public string Country_Code { get; set; }

    [Required]
    [StringLength(5)]
    [Unicode(false)]
    public string Default_Language_Id { get; set; }

    [InverseProperty("Country")]
    public virtual ICollection<tblLanguageDetail> tblLanguageDetails { get; set; } = new List<tblLanguageDetail>();

    [InverseProperty("Country")]
    public virtual ICollection<tblWidget> tblWidgets { get; set; } = new List<tblWidget>();
}