// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace SimpleOtisAPI.Domain.Models;

public partial class tblLanguageDetail
{
    [Key]
    public int Language_Id { get; set; }

    [JsonIgnore]
    public int Country_Id { get; set; }

    [Required]
    [StringLength(5)]
    [Unicode(false)]
    public string Language_Code { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Language_Name { get; set; }

    [JsonIgnore]
    [ForeignKey("Country_Id")]
    [InverseProperty("tblLanguageDetails")]
    public virtual tblCountryDetail Country { get; set; }

    [JsonIgnore]
    [InverseProperty("Language")]
    public virtual ICollection<tblWidget> tblWidgets { get; set; } = new List<tblWidget>();
}