// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace SimpleOtisAPI.Domain.Models
{

    public class tblPreference
    {
        [Key]
        public int Preference_Id { get; set; }

        public int User_Id { get; set; }

        public int Selected_Language_Id { get; set; }

        public int? Theme_Id { get; set; }

        public string Theme_Name { get; set; }

        [JsonIgnore]
        [ForeignKey("Theme_Id")]
        [InverseProperty("tblPreferences")]
        public virtual tblTheme Theme { get; set; }

        //[Required]
        //public List<tblLanguageDetail> LanguageList { get; set; }

        [JsonIgnore]
        public string Language_List { get; set; }
        public List<LanguageList> LanguageList { get; set; }
    }

    public class LanguageList
    {
        public int Id { get; set; }
        public string Language_Code { get; set; }
        public string Language_Name { get; set; }
    }
}

