// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SimpleOtisAPI.Domain.Models;

[Table("tblTheme")]
public partial class tblTheme
{
    [Key]
    public int Theme_Id { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Theme_Name { get; set; }

    [InverseProperty("Theme")]
    public virtual ICollection<tblPreference> tblPreferences { get; set; } = new List<tblPreference>();
}