// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace SimpleOtisAPI.Domain.Models;

[Table("tblWidget")]
public partial class tblWidget
{
    [JsonIgnore]
    [Key]
    public int Widget_Id { get; set; }

    public int Emergency_Callbacks { get; set; }

    public int Non_Emergency_Callbacks { get; set; }

    public int Total_Callbacks { get; set; }

    public string Country_Code { get; set; }

    public string Language_Code { get; set; }

    [JsonIgnore]
    //[ForeignKey("Country_Id")]
    [InverseProperty("tblWidgets")]
    public virtual tblCountryDetail Country { get; set; }

    [JsonIgnore]
    //[ForeignKey("Language_Id")]
    [InverseProperty("tblWidgets")]
    public virtual tblLanguageDetail Language { get; set; }
}